server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
spring:
  application:
    name: frontend
  profiles:
    active: local
  config:
    import: optional:configserver:${CONFIG_SERVER}

  devtools:
    livereload:
      port: 35734
